src/Entity/Submission.php
<?php

declare(strict_types=1);

namespace KUL\FormBundle\Entity;

use KUL\FormBundle\Client\AnswerValue\Value;
use KUL\FormBundle\Client\AnswerValue\ValueCollection;
use KUL\FormBundle\Client\History\HistoryDateFormatter;
use KUL\FormBundle\Client\History\InputNodeSubmitEntry;
use KUL\FormBundle\Client\History\SubmitHistory;
use KUL\FormBundle\Client\Submission\SubmissionCollection;
use KUL\FormBundle\Domain\Contract\FormUserInterface;
use KUL\FormBundle\Domain\Template\Contract\StepInterface;
use KUL\FormBundle\Domain\Template\Element\FormList;
use KUL\FormBundle\Domain\Template\Element\Node\Contract\ParentalInputNode;
use KUL\FormBundle\Domain\Template\Element\Node\Question\InputNode;
use KUL\FormBundle\Domain\Template\Element\WorkFlow;
use KUL\FormBundle\Domain\Utility\Role;
use Ramsey\Uuid\Uuid;

/**
 * Values submitted by a user, who filled out a symfony form based on a template.
 *
 * @see     SubmissionCollection
 */
class Submission
{
    private readonly string $id;
    /**
     * refers to step in @see WorkFlow in which user has saved/submitted.
     */
    private string $stepUid;
    private readonly string $role;
    private ?\DateTimeImmutable $originalSubmitDateBeforeRollback = null;

    private function __construct(
        private readonly string $submitterId,
        private readonly string $submitterFullName,
        private readonly int $versionNumber,
        private string $values,
        string $role,
        string $stepUid,
        private \DateTimeImmutable $submitDate,
        private readonly bool $autoSaved = false,
    ) {
        if ('' === $role) {
            throw new \InvalidArgumentException('submission role must be a non empty string.');
        }

        if ('' === $stepUid) {
            throw new \InvalidArgumentException('submission stepUid must be a non empty string.');
        }

        $this->id = Uuid::uuid4()->toString();
        $this->stepUid = $stepUid;
        $this->role = $role;
    }

    public static function createFromUserWithRoleInStepForValuesByVersionOnDate(
        FormUserInterface $user,
        Role $role,
        StepInterface $step,
        ValueCollection $values,
        int $versionNumber,
        \DateTimeImmutable $date,
        bool $autoSaved,
    ): self {
        return new self(
            $user->getIdentifier(),
            $user->getPerson()->getFullName(),
            $versionNumber,
            self::getValuesString($values),
            $role->getName(),
            $step->getUid(),
            $date,
            $autoSaved
        );
    }

    public static function createFromDataWithValues(
        string $submitterId,
        string $submitterFullName,
        int $versionNumber,
        ValueCollection $values,
        string $role,
        string $stepUid,
        \DateTimeImmutable $submitDate,
        bool $autoSaved = false,
    ): self {
        return new self(
            $submitterId,
            $submitterFullName,
            $versionNumber,
            self::getValuesString($values),
            $role,
            $stepUid,
            $submitDate,
            $autoSaved
        );
    }

    public function convertForRollbackByDate(\DateTimeImmutable $rollbackDate): void
    {
        // the original submitDate is stored redundantly to indicate submission was updated by rollback.
        $this->originalSubmitDateBeforeRollback = clone $this->submitDate;
        // the new submitDate is now the one from Rollback, so that the chronology of logs can be dealt with consequently (on submit dates).
        $this->submitDate = $rollbackDate;
    }

    public function isConvertedByRollback(): bool
    {
        return $this->originalSubmitDateBeforeRollback instanceof \DateTimeImmutable;
    }

    private static function getValuesString(ValueCollection $values): string
    {
        return json_encode($values, \JSON_THROW_ON_ERROR);
    }

    public function getId(): string
    {
        return $this->id;
    }

    public function getSubmitterId(): string
    {
        return $this->submitterId;
    }

    public function getSubmitterFullName(): string
    {
        return $this->submitterFullName;
    }

    public function getVersionNumber(): int
    {
        return $this->versionNumber;
    }

    public function getSubmitDate(): \DateTimeImmutable
    {
        return $this->submitDate;
    }

    public function getSubmitDateString(?string $locale = null): string
    {
        return HistoryDateFormatter::format($this->getSubmitDate(), $locale);
    }

    public function getOriginalSubmitDateBeforeRollback(): \DateTimeImmutable
    {
        if (!$this->originalSubmitDateBeforeRollback instanceof \DateTimeImmutable) {
            throw new \Exception('no originalSubmitDateBeforeRollback found in submission!');
        }

        return $this->originalSubmitDateBeforeRollback;
    }

    public function getOriginalSubmitDateBeforeRollbackString(?string $locale = null): string
    {
        return HistoryDateFormatter::format($this->getOriginalSubmitDateBeforeRollback(), $locale);
    }

    public function getStepUid(): string
    {
        return $this->stepUid;
    }

    public function getRole(): string
    {
        return $this->role;
    }

    public function getValues(): ValueCollection
    {
        $values = [];
        foreach (json_decode($this->values, true, 512, \JSON_THROW_ON_ERROR) as $item) {
            $values[] = Value::createFromArray($item);
        }

        return new ValueCollection($values);
    }

    /**
     * is this submission the consequence of an auto save operation.
     */
    public function isAutoSaved(): bool
    {
        return $this->autoSaved;
    }

    /**
     * @throws \Exception
     */
    public function getSubmitHistoryForFormList(FormList $formList): SubmitHistory
    {
        $entries = [];
        /** @var Value $value */
        foreach ($this->getValues() as $value) {
            if (!$formList->hasNodeByUid($value->getUid())) {
                continue;
            }

            $node = $formList->getNodeByUid($value->getUid());
            if (!$node instanceof InputNode) {
                continue;
            }

            if (!$node instanceof ParentalInputNode) {
                continue;
            }

            $originalSubmitDateBeforeRollback = null;
            if ($this->isConvertedByRollback()) {
                $originalSubmitDateBeforeRollback = $this->getOriginalSubmitDateBeforeRollback();
            }

            $entries[] = InputNodeSubmitEntry::fromNodeAndDateAndValue(
                $node,
                $this->getSubmitDate(),
                $value->getValue(),
                $this->getSubmitterId(),
                $this->getSubmitterFullName(),
                $this->getStepUid(),
                $this->getRole(),
                $value->isAutoAdded(),
                $this->isAutoSaved(),
                $originalSubmitDateBeforeRollback
            );
        }

        return new SubmitHistory($entries);
    }

    /**
     * update an existing submission marked for auto save by another (i.e. more recent) submission marked for auto save,
     * for the same submitter (user identifier), role, step and (template) version.
     * this allows to avoid database overload with many submissions for auto save for the same UNIQUE combination of
     * user-role-step-version auto saving every x minutes for the same @see StoredTemplateTarget
     * note: submissions (history logs about form actions) should never be changed. but this is an exception required
     * and necessary for database capacity reasons, and it only allows for auto saved actions, no manually saved actions
     * note: the submitters id must be the same but the full name of the submitter can be different (in case of name
     * changes. the submitter full name is pure metadata, no identifying data).
     */
    public function updateBySubmissionForAutoSave(self $submission): void
    {
        if (!$this->isAutoSaved()) {
            throw new \DomainException('cannot update for autosave: source submission is not marked as autoSaved.');
        }

        if (!$submission->isAutoSaved()) {
            throw new \DomainException('cannot update for autosave: given submission is not marked as autoSaved.');
        }

        if ($this->getSubmitterId() !== $submission->getSubmitterId()
            || $this->getRole() !== $submission->getRole()
            || $this->getStepUid() !== $submission->getStepUid()
            || $this->getSubmitterId() !== $submission->getSubmitterId()
        ) {
            throw new \DomainException('cannot update for autosave: identifying auto save data of source and given submissions do not match.');
        }

        $this->submitDate = $submission->getSubmitDate();
        $this->values = self::getValuesString($submission->getValues());
    }

    public function fixStepUid(string $stepUid): void
    {
        $this->stepUid = $stepUid;
    }
}

src/Resources/views/embed/history/embed/macros.html.twig
{% trans_default_domain 'kulFormHistory' %}

{% macro renderSubmission(savedInfoMessageTranslationKey, submission, currentVersionNumber, showSubmitterId, roleSlugifier) %}
    {% import _self as macros %}
    {% set submissionIsConvertedByRollback = submission.isConvertedByRollback %}

    {% if submission.isAutoSaved %}
        <span><span class='label label-default'>{{ 'workflow.submission.autoSaved'|trans }}</span></span>
    {% endif %}

    {% if submissionIsConvertedByRollback %}
        <span><span class='label label-default'>{{ ('workflow.submission.savedInfoMessage.convertedByRollback')|trans }}</span></span>
    {% endif %}

    <strong>{{ ('workflow.submission.savedInfoMessage.' ~ savedInfoMessageTranslationKey)|trans }}</strong>
    {{ 'workflow.submission.savedInfoMessage.on'|trans }}

    <strong>{{ submission.getSubmitDateString(app.request.locale) }}</strong>

    {% if submissionIsConvertedByRollback %}
        {{ ('workflow.submission.savedInfoMessage.and')|trans }} <strong> {{ ('workflow.submission.savedInfoMessage.originallySubmitted')|trans }} </strong>
    {% endif %}

    {{ 'workflow.submission.savedInfoMessage.by'|trans }}
    <strong>
        {{ submission.submitterFullName }}
        ({{ 'workflow.submission.savedInfoMessage.as'|trans }}
        {{ roleSlugifier.hasSlugForRole(submission.role) ? roleSlugifier.getSlugForRole(submission.role) : submission.role }})
    </strong>
    {% if showSubmitterId is defined and showSubmitterId %}
        ({{ 'workflow.submission.submitterId'|trans }}: {{ submission.submitterId }})
    {% endif %}

    {% if submissionIsConvertedByRollback %}
        {{ 'workflow.submission.savedInfoMessage.on'|trans }} <strong> {{ submission.getOriginalSubmitDateBeforeRollbackString(app.request.locale) }} </strong>
    {% endif %}

    {% if submission.versionNumber != currentVersionNumber %}
        <span class="text-danger">
		 ({{ 'workflow.submission.olderVersionWarning'|trans({'%number%': submission.versionNumber})|raw }})
	    </span>
    {% endif %}
{% endmacro %}

src/Resources/views/embed/history/embed/step-submissions.html.twig
{% trans_default_domain 'kulFormHistory' %}
{% import "@KULForm/embed/history/embed/macros.html.twig" as macros %}

{#  making sure the submissions passed in are for the passed in step & nicely ordered (after all, this is an embeddable) #}
{% set stepSubmissions = stepSubmissions.forStep(flowStep).sortedByDescendingSubmitDate %}
{% set stepTempSubmissions = stepTempSubmissions.forStep(flowStep).sortedByDescendingSubmitDate %}

<table class="table table-bordered mb10" width="100%">
    <tbody>
    <tr>
        <th>
            <em>
                {{ 'workflow.step.stepNumber'|trans({'%number%': stepPositionNr}) }}
            </em>
            {% if statusTimeline is same as('past') %}
                <span class='label label-danger'>{{ 'workflow.step.past.state'|trans }}</span>
            {% elseif statusTimeline is same as('current') %}
                <span class='label label-success'>{{'workflow.step.current.state'|trans }}</span>
            {% elseif statusTimeline is same as('future') %}
                <span class='label label-info'>{{ 'workflow.step.future.state'|trans }}</span>
            {% endif %}
            ({{ flowStep.label(app.request.locale) }})
            {% if showStepOpenRange|default(false) %}
                {% if kul_form_stepUsesFixedDates(flowStep) %}
                    ({{ ('workflow.step.openRange'|trans({
                    '%start%': flowStep.period.fixedStartDate|date,
                    '%end%':  flowStep.period.fixedEndDate|date
                }))|raw }})
                {% elseif kul_form_stepUsesCalculatedDates(flowStep) and calculatedStepReferenceDate|default(null) is not empty %}
                    ({{ ('workflow.step.openRange'|trans({
                    '%start%': flowStep.period.calculatedStartDate(calculatedStepReferenceDate)|date,
                    '%end%': flowStep.period.calculatedEndDate(calculatedStepReferenceDate)|date
                }))|raw }})
                {% endif %}
            {% endif %}
        </th>
    </tr>

    {# steps that have not yet started (future steps) do not have any submissions history #}
    {% if statusTimeline is not same as('future') %}
        <tr>
            <td>
                {# perfectly possible that nobody ever submitted in a past (closed) step and/or in current step#}
                {% if stepSubmissions.isEmpty and stepTempSubmissions.isEmpty %}
                    {% if statusTimeline is same as('past') %}
                        <p><strong>{{ ('workflow.submission.noneSubmitted'|trans)|raw }}</strong></p>
                    {% else %}
                        <p>
                            <strong>{{ ('workflow.submission.noneSubmittedYet'|trans)|raw }}<br/>
                                <span class="text-muted">{{ ('workflow.submission.noneTempSavedYet'|trans)|raw }}</span>
                            </strong>
                        </p>
                    {% endif %}
                {% else %}
                    {% set latestSubmission = stepSubmissions.first %}
                    {# always show last submitted if at least someone has submitted in this step #}
                    {% if latestSubmission is not empty %}
                        {# a step ended either when its end date was reached, or it ended before that date when a single
                           user's submit action in that step caused the next step to start prematurely. the message of
                           the last submit action should reflect that difference #}
                        {% set transKey = 'lastSubmitted' %}
                        {% if statusTimeline is same as('past') and checkDate|default(null) is not empty%}
                            {% if kul_form_stepUsesFixedDates(flowStep) and not flowStep.isEndedByDate(checkDate) %}
                                {% set transKey = 'ended' %}
                            {% elseif kul_form_stepUsesCalculatedDates(flowStep) and calculatedStepReferenceDate|default(null) is not empty and not flowStep.isEndedByDate(checkDate, calculatedStepReferenceDate) %}
                                {% set transKey = 'ended' %}
                            {% endif %}
                        {% endif %}
                        <p>
                            {{ macros.renderSubmission(
                                transKey,
                                latestSubmission,
                                currentVersionNumber,
                                showSubmitterIds,
                                roleSlugifier)
                            }}
                        </p>
                    {% else %}
                        {# always explicitly inform if no one has submitted in current step or previous step #}
                        {% if statusTimeline is same as('past') %}
                            <p>{{ ('workflow.submission.noneSubmitted'|trans)|raw }}</p>
                        {% else %}
                            <p>{{ ('workflow.submission.noneSubmittedYet'|trans)|raw }}</p>
                        {% endif %}
                    {% endif %}

                    {# in the current step, show who last temporary saved (shows progress) #}
                    {% if statusTimeline is same as('current') %}
                        {% set latestTempSubmission = stepTempSubmissions.first %}
                        {% if latestTempSubmission is not empty %}
                            <p class="text-muted">
                                {{ macros.renderSubmission(
                                    'lastTempSaved',
                                    latestTempSubmission,
                                    currentVersionNumber,
                                    showSubmitterIds,
                                    roleSlugifier)
                                }}
                            </p>
                        {% else %}
                            <p class="text-muted">
                                {{ ('workflow.submission.noneTempSavedYet'|trans)|raw }}
                            </p>
                        {% endif %}
                    {% endif %}

                    {# list all submissions, both temporary and final all mixed in and in order of descending date #}
                    {% set allStepSubmissions = stepSubmissions.mergedWith(stepTempSubmissions).sortedByDescendingSubmitDate %}
                    <table class="table table-bordered mb0" width="100%">
                        <tbody>
                        <tr>
                            <td>
                                <a href="#" class="step-submissions-collapser"
                                   data-target-class="step-{{ flowStep.uid }}-submission"
                                   title="{{ 'workflow.submission.clickForMore'|trans }}">
                                    {{ 'workflow.submission.clickForMore'|trans }}
                                    <span class="text-muted">{{ '(' ~ ('workflow.submission.orderedByDescDate'|trans) ~ ')' }}</span>
                                </a>
                            </td>
                        </tr>
                        {% for submission in allStepSubmissions %}
                            {% set isTempSubmission = stepTempSubmissions.contains(submission) %}
                            <tr class="step-submission step-{{ flowStep.uid }}-submission" style="display: none;">
                                <td class="{{ isTempSubmission ? 'text-muted' : '' }}">
                                    {{ macros.renderSubmission(
                                        isTempSubmission ? 'tempSaved' : 'submitted',
                                        submission,
                                        currentVersionNumber,
                                        showSubmitterIds,
                                        roleSlugifier)
                                    }}
                                </td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                {% endif %}
            </td>
        </tr>
    {% endif %}
    </tbody>
</table>